<% project_name = 'meditation-app-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: <%= project_name %>_development
  # password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: <%= project_name %>_test
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
